version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 5
    reviewers:
      - brpaz
    labels:
      - dependencies
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 5
    reviewers:
      - brpaz
    labels:
      - dependencies
