[build]
command = "yarn generate"
ignore = "git log -1 --pretty=%B | grep dependabot"
publish = "dist/"

[build.environment]
NODE_ENV = "production"
NODE_VERSION = "14"

# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
# set TERM variable for terminal output
TERM = "xterm"

[[plugins]]
# local Cypress plugin will test our site after it is built
package = "netlify-plugin-cypress"

[[headers]]
for = "/*"
[headers.values]
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

[[redirects]]
force = true
from = "https://brunopaz.netlify.com/*"
status = 301
to = " https://brunopaz.dev/:splat"
