name: CI
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn install
      - run: yarn lint

  build:
    runs-on: ubuntu-18.04
    needs: lint
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: cp env.sample .env
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@master
        with:
          name: Application Code
          path: /dist

  # lighthouse-check:
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@master
  #     - run: mkdir /tmp/artifacts
  #     - name: Run Lighthouse
  #       uses: foo-software/lighthouse-check-action@master
  #       with:
  #         accessToken: ${{ secrets.GITHUB_TOKEN }}
  #         author: ${{ github.actor }}
  #         branch: ${{ github.ref }}
  #         outputDirectory: /tmp/artifacts
  #         urls: 'https://localhost:'
  #         sha: ${{ github.sha }}
  #     - name: Upload artifacts
  #       uses: actions/upload-artifact@master
  #       with:
  #         name: Lighthouse reports
  #         path: /tmp/artifacts
