name: Update draft release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - uses: brpaz/draftsman@c3261902eee44ae9474603d8578c13fafb5c2c66 # v0.3.0
        with:
          command: draft
          backend: github
          token: ${{ secrets.GITHUB_TOKEN }}
