name: Deploy to Cloudflare Pages

on:
  release:
    types: [published]

env:
  SITE_URL: https://brunopaz.dev

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Update CHANGELOG
        uses: stefanzweifel/changelog-updater-action@a938690fad7edf25368f37e43a1ed1b34303eb36 # v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Bump version
        run: |
          npm version ${{ github.event.release.tag_name }} --no-git-tag-version

      - name: Commit updated files
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        with:
          branch: main
          commit_message: 'chore(release): [skip ci] ${{ github.event.release.tag_name }}'
          file_pattern: CHANGELOG.md package.json

  deploy:
    name: Deploy Production
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    environment:
      name: production
      url: https://brunopaz.dev
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
        with:
          run_install: false

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build production artifact
        run: pnpm build
        env:
          SITE_URL: ${{ env.SITE_URL }}
          PUBLIC_SENTRY_KEY: ${{ secrets.PUBLIC_SENTRY_KEY }}
          PUBLIC_WEB_MONETIZATION_ID: ${{ secrets.PUBLIC_WEB_MONETIZATION_ID }}
          PUBLIC_SENTRY_ENABLED: 'true'

      - name: Update version.txt
        run: |
          cat <<-EOF > ${{ env.VERSION_FILE }}
            Version: ${{ github.event.release.tag_name }}
            Commit: ${{ github.sha }}
            Date: $(date --iso-8601=seconds)
          EOF
        env:
          VERSION_FILE: dist/version.txt

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # v1.5.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME }}
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
