name: Deploy to Cloudflare Pages

on:
  release:
    types: [published]

env:
  SITE_URL: https://brunopaz.dev

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment:
      name: production
      url: https://brunopaz.dev
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ".node-version"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
        env:
          PUBLIC_FORMSPREE_FORM_ID: ${{ secrets.PUBLIC_FORMSPREE_FORM_ID }}
          PUBLIC_SENTRY_KEY: ${{ secrets.PUBLIC_SENTRY_KEY }}
          PUBLIC_WEB_MONETIZATION_ID: ${{ secrets.PUBLIC_WEB_MONETIZATION_ID }}
          BASE_URL: ${{ env.SITE_URL }}
          PUBLIC_CHAT_ENABLED: "true"
          PUBLIC_SENTRY_ENABLED: "true"

      - name: Test
        run: pnpm test

      - name: Update CHANGELOG
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG and README files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "chore(release): [skip-ci] ${{ github.event.release.tag_name }}"
          file_pattern: CHANGELOG.md

      - name: Deploy to Production
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME }}
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main

